# Generated by Django 6.0.6 on 2026-06-05 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='font_size',
            field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default='MEDIUM', help_text="Tamaño de la tipografía preferida por el usuario para accesibilidad ('SMALL', 'MEDIUM', 'LARGE').", max_length=10),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='high_contrast',
            field=models.BooleanField(default=False, help_text='Preferencia de visualización de colores con contraste elevado para accesibilidad.'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='user',
            field=models.OneToOneField(help_text='Usuario Django propietario de esta configuración.', on_delete=django.db.models.deletion.CASCADE, related_name='config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='voice_guidance',
            field=models.BooleanField(default=False, help_text='Preferencia de navegación asistida por comandos y locución de voz.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.CharField(blank=True, help_text='URL de la imagen de avatar o foto de perfil del usuario.', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, help_text='Número telefónico de contacto del usuario.', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(help_text='Usuario Django propietario de este perfil.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
